In [2]:
import numpy as np

In [3]:
my_list = list(range(1000000))
type(my_list)

list

In [7]:
my_arr = np.arange(1000000)
type(my_arr)

numpy.ndarray

In [10]:
%time
for _ in range(10):
    myarr2 = my_arr * 2

Wall time: 0 ns


In [13]:
%time
for _ in range(10):
    mylist2 = my_list *2

Wall time: 0 ns


In [21]:
data = np.random.randn(5,3,3)
data

array([[[-7.48609163e-01,  1.76922905e-01, -1.53421425e-01],
        [ 1.03560957e+00,  1.78709195e+00, -1.23315253e+00],
        [ 4.67499549e-01,  1.34779801e-01, -1.58344297e+00]],

       [[-1.83252981e+00,  8.51223295e-01,  4.87256172e-01],
        [ 1.63873678e-01, -1.12181060e-02, -2.81337327e-01],
        [-1.94852865e-02,  1.42891038e+00, -3.32571624e-01]],

       [[-1.07759421e+00,  7.74686263e-01, -5.54310750e-01],
        [ 8.56037776e-02,  7.49460618e-01, -2.86397238e-01],
        [-7.18125151e-01, -5.75560456e-01, -3.62631919e-01]],

       [[-1.15736884e-01,  1.52174617e+00, -9.51935064e-01],
        [-9.49440316e-02, -8.43710565e-04, -5.78981729e-01],
        [-1.83470113e-01, -3.71624411e-02,  1.49077159e-01]],

       [[ 5.46893231e-01, -2.26575077e-02,  4.91141945e-01],
        [-3.35476987e-01, -1.43095052e+00, -1.05263575e+00],
        [-2.88453966e-01,  5.78302265e-01, -5.16945378e-01]]])

In [16]:
data.ndim

2

In [22]:
data1 = np.random.randn(2,2)
data1

array([[ 1.07914782, -0.25637658],
       [ 0.6828859 , -0.72133708]])

In [31]:
data1= data1 * 2
print(data1)

[[ 2.15829565 -0.51275316]
 [ 1.3657718  -1.44267416]]


In [25]:
data2 = np.random.randn(2,2)
data2

array([[ 0.09169885,  1.78967171],
       [-0.32194816,  0.9168884 ]])

In [32]:
print(data1)

[[ 2.15829565 -0.51275316]
 [ 1.3657718  -1.44267416]]


In [33]:
data1 - data2

array([[ 2.06659679, -2.30242487],
       [ 1.68771996, -2.35956256]])

In [34]:
data1+data2

array([[ 2.2499945 ,  1.27691856],
       [ 1.04382364, -0.52578576]])

In [35]:
data1 * data2

array([[ 0.19791324, -0.91765982],
       [-0.43970772, -1.3227712 ]])

In [36]:
data1 / data2

array([[23.53677878, -0.28650682],
       [-4.24221025, -1.57344576]])

In [37]:
data1 % data2

array([[ 0.049222  ,  1.27691856],
       [-0.24396902,  0.39110264]])

In [40]:
data1 @ data2 #matrix multiplication

array([[0.36299317, 3.39250324],
       [0.58970601, 1.12151195]])

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
arr3=np.arange(1,25).reshape(2,3,4)
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [4]:
arr3[1][1][2]

19

In [45]:
arr3[1,0::,:3:1]

array([[13, 14, 15],
       [17, 18, 19],
       [21, 22, 23]])

In [59]:
arr4=np.arange(50,100).reshape(2,5,5)
arr4

array([[[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])